import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        brand: {
          purple: "#37003C",
          green:  "#00FF87",
          cyan:   "#04F5FF",
        },
        background:     "#F7F6FA",
        surface:        "#FFFFFF",
        "surface-alt":  "#F4F3F8",
        "text-primary": "#1A1A2E",
        "text-secondary": "#6B7280",
        border:   "#E5E7EB",
        success:  "#10B981",
        error:    "#EF4444",
        warning:  "#F59E0B",
        gold:     "#FFD700",
        silver:   "#C0C0C0",
        bronze:   "#CD7F32",
        // Shadcn compat
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        input: "hsl(var(--input))",
        ring:  "hsl(var(--ring))",
        chart: { "1": "hsl(var(--chart-1))", "2": "hsl(var(--chart-2))", "3": "hsl(var(--chart-3))", "4": "hsl(var(--chart-4))", "5": "hsl(var(--chart-5))" },
      },
      fontFamily: {
        sans:    ["var(--font-barlow)", "system-ui", "sans-serif"],
        mono:    ["var(--font-jetbrains)", "JetBrains Mono", "Consolas", "monospace"],
        display: ["var(--font-barlow-condensed)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg:   "var(--radius)",
        md:   "calc(var(--radius) - 2px)",
        sm:   "calc(var(--radius) - 4px)",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        "glow-green":  "0 0 30px rgba(0,255,135,0.35)",
        "glow-green-sm": "0 0 15px rgba(0,255,135,0.2)",
        "glow-purple": "0 0 30px rgba(55,0,60,0.4)",
        "card":        "0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04)",
        "card-hover":  "0 4px 20px rgba(0,0,0,0.10), 0 1px 4px rgba(0,0,0,0.06)",
        "deep":        "0 20px 60px rgba(55,0,60,0.15)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "pulse-green":    { "0%, 100%": { boxShadow: "0 0 0 0 rgba(0,255,135,0.4)" }, "50%": { boxShadow: "0 0 0 8px rgba(0,255,135,0)" } },
        "slide-up":       { from: { opacity: "0", transform: "translateY(20px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in":        { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in":       { from: { opacity: "0", transform: "scale(0.95)" }, to: { opacity: "1", transform: "scale(1)" } },
        shimmer:          { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        float:            { "0%, 100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-8px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "pulse-green":    "pulse-green 2s infinite",
        "slide-up":       "slide-up 0.4s cubic-bezier(0.16,1,0.3,1) both",
        "fade-in":        "fade-in 0.3s ease both",
        "scale-in":       "scale-in 0.35s cubic-bezier(0.16,1,0.3,1) both",
        shimmer:          "shimmer 2s linear infinite",
        float:            "float 4s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config